apiVersion: batch/v1
kind: Job
metadata:
  name: odoo-upgrade-job
spec:
  template:
    spec:
      containers:
      - name: upgrade
        image: REPLACE_IMAGE_TAG
        command: ["/bin/bash", "-c"]
        args: 
          - |
            /custom-entrypoint.sh odoo -d odoo_produccion -u all --stop-after-init || /custom-entrypoint.sh odoo -d odoo_produccion -i web --stop-after-init
        env:
        - name: DB_HOST
          valueFrom: { secretKeyRef: { name: odoo-db-secrets, key: db_host } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: odoo-db-secrets, key: db_user } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: odoo-db-secrets, key: db_password } }
        - name: ADMIN_PASSWORD
          valueFrom: { secretKeyRef: { name: odoo-db-secrets, key: admin_password } }
        - name: DB_NAME
          valueFrom: { secretKeyRef: { name: odoo-db-secrets, key: db_name } }
      restartPolicy: OnFailure