[jenkins_server]
# Se Remplaza con la ip publica que de terraform
YOUR_EC2_PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/aws/jenkins_key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'